library(tidyverse)
setwd("C:/Users/samha/Documents/GitHub/Optimality-Bias")
optdata <- read.csv("R_Manuscript_Dataset.csv")
optdata <- as_tibble(optdata)
write.csv(optdata, "C:/Users/samha/Documents/GitHub/Optimality-Bias/test.csv")
optdata <- read.csv("test.csv")
optdata <- select(optdata, 3:ncol(optdata))
optdata <- select(optdata, -starts_with("fir"))
optdata <- select(optdata, -ends_with("1") & -ends_with("2"))
optdata <- select(optdata, 5:17, 1:2, 18:ncol(optdata))
optdata <- select(optdata, 5 | 8 | 12:ncol(optdata))
optdata <- select(optdata, 3:8, 10:11, 9, 1:2)
optdata <- arrange(optdata, optdata$choice, optdata$expert)
write.csv(optdata, "C:/Users/samha/Documents/GitHub/Optimality-Bias/clean.csv")
optdata <- read.csv("clean.csv") %>% select(-1)
